Moved the setting of ntlm properties to earlier in the creation of JI…
skyghis/j-interop-ng pull request #17
Opened 2022-12-14 10:48 UTC by pgharron

…ComServer.  This ensures the authentication level is at its highest for the initial connection.

Hi @skyghis , this is the change.  Please let me know if you think it's OK. 
Many Thanks
Phil

2022-12-15 17:20 UTC, skyghis approved these changes

2022-12-15 17:20 UTC, skyghis requested changes
Can you add a line in the CHANGELOG please ?

2022-12-15 17:46 UTC, pgharron commented
I've updated the CHANGELOG.  
Thanks

2022-12-16 13:27 UTC, skyghis commented
I have merged this PR via Cheery-pick because of another change on some old commits.
Force a full repo sync because some old commit SHA1 have changed.

Thanks for the changes.

2022-12-16 13:27 UTC, closed without merging